[package]
name = "gbc-rs"
version = "0.1.0"
authors = ["David Avedissian <git@dga.me.uk>"]

[dependencies]
time = "0.1.38"
unborrow = "0.3.1"
rasteriser = { git = "https://github.com/davedissian/rasteriser.git" }